- name: Set up node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '24'

      - name: Install Angular cli
        run: npm install -g @angular/cli@20

      - name: Install deps and build angular app
        run: |
          cd client
          npm install
          ng build
